FROM python:3.11-slim

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false

RUN pip install poetry

WORKDIR /usr/src/app

COPY pyproject.toml .
COPY poetry.lock .

# production
# RUN poetry install --without dev --no-root --no-directory

# dev
RUN poetry install --no-root --no-directory

COPY --link . .

# production
# CMD ["gunicorn", "app.main:app"]

# dev
CMD ["uvicorn", "app.main:app", "--host=0.0.0.0", "--loop=uvloop", "--port=9999"]
