services:
  minio:
    image: pgsty/silo:RELEASE.2026-09-03T13-18-01Z
    container_name: bombus-minio-common
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      TZ: Asia/Taipei
    volumes:
      - ./data:/data
