version: '3.7'
services:
  ### web ###
  web:
    image: local_laravel_app
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ~/local/docroot:/var/www/html/docroot
    ports:
      - '80:80'
      - '443:443'
    privileged: true

  ### mysql ###
  mysql:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    privileged: true
  ### Postgres ################################################
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=laravel
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  ### redis ###
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  mysql:
  postgres:
