version: '3.8'

services:
  app:
    build:
      context: .
    image: local_node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    entrypoint:
      - bash
      - -c
      - yarn && yarn dev
