services:
  redis-master:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --bind
      - 0.0.0.0
      - --protected-mode
      - "no"
      - --port
      - "6379"
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --replica-announce-ip
      - ${VM_IP}
      - --replica-announce-port
      - "6379"

    volumes:
      - ./data/sentinel/master:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


  redis-replica-1:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "6380:6379"

    command:
      - redis-server
      - --bind
      - 0.0.0.0
      - --protected-mode
      - "no"
      - --port
      - "6379"
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --replicaof
      - redis-master
      - "6379"
      - --replica-announce-ip
      - ${VM_IP}
      - --replica-announce-port
      - "6380"

    volumes:
      - ./data/sentinel/replica-1:/data

    depends_on:
      redis-master:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


  redis-replica-2:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "6381:6379"

    command:
      - redis-server
      - --bind
      - 0.0.0.0
      - --protected-mode
      - "no"
      - --port
      - "6379"
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --replicaof
      - redis-master
      - "6379"
      - --replica-announce-ip
      - ${VM_IP}
      - --replica-announce-port
      - "6381"

    volumes:
      - ./data/sentinel/replica-2:/data

    depends_on:
      redis-master:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


  redis-sentinel-1:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "26379:26379"

    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica-1:
        condition: service_healthy
      redis-replica-2:
        condition: service_healthy

    command:
      - sh
      - -c
      - |-
        if [ ! -f /data/sentinel.conf ]; then
          cat > /data/sentinel.conf <<EOF
        bind 0.0.0.0
        protected-mode no
        port 26379
        dir /data

        sentinel monitor mymaster ${VM_IP} 6379 2
        sentinel down-after-milliseconds mymaster 5000
        sentinel failover-timeout mymaster 60000
        sentinel parallel-syncs mymaster 1

        sentinel announce-ip ${VM_IP}
        sentinel announce-port 26379
        EOF
        fi

        exec redis-sentinel /data/sentinel.conf

    volumes:
      - ./data/sentinel/sentinel-1:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


  redis-sentinel-2:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "26380:26379"

    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica-1:
        condition: service_healthy
      redis-replica-2:
        condition: service_healthy

    command:
      - sh
      - -c
      - |-
        if [ ! -f /data/sentinel.conf ]; then
          cat > /data/sentinel.conf <<EOF
        bind 0.0.0.0
        protected-mode no
        port 26379
        dir /data

        sentinel monitor mymaster ${VM_IP} 6379 2
        sentinel down-after-milliseconds mymaster 5000
        sentinel failover-timeout mymaster 60000
        sentinel parallel-syncs mymaster 1

        sentinel announce-ip ${VM_IP}
        sentinel announce-port 26380
        EOF
        fi

        exec redis-sentinel /data/sentinel.conf

    volumes:
      - ./data/sentinel/sentinel-2:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


  redis-sentinel-3:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "26381:26379"

    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica-1:
        condition: service_healthy
      redis-replica-2:
        condition: service_healthy

    command:
      - sh
      - -c
      - |-
        if [ ! -f /data/sentinel.conf ]; then
          cat > /data/sentinel.conf <<EOF
        bind 0.0.0.0
        protected-mode no
        port 26379
        dir /data

        sentinel monitor mymaster ${VM_IP} 6379 2
        sentinel down-after-milliseconds mymaster 5000
        sentinel failover-timeout mymaster 60000
        sentinel parallel-syncs mymaster 1

        sentinel announce-ip ${VM_IP}
        sentinel announce-port 26381
        EOF
        fi

        exec redis-sentinel /data/sentinel.conf

    volumes:
      - ./data/sentinel/sentinel-3:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
